services:
  gz-simulator:						# Compose service name (internal identifier)
    build:
      context: .					
    image: ros-jazzy-gz-simulator
    container_name: ros-jazzy-gz-simulator		# Final name of running container
    privileged: true
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    gpus : all
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=42       
    volumes:
      - /dev:/dev:rw
      - /media:/media:rw
      - /etc/timezone:/etc/timezone:rw
      - /etc/localtime:/etc/localtime:rw
      #ros-workspaces
      - ./ws:/root/ros_jazzy_ws/:rw      
    entrypoint: /bin/bash      
    
    
    
    
